services:
  postgres:
    image: postgres:15-alpine
    container_name: saas_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: saas_calendar
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d saas_calendar"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./PA-SaaS2
    container_name: saas_backend
    ports:
      - "8080:8080"
    environment:
      # Spring Boot leerá automáticamente estas variables
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/saas_calendar
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend-saas
    container_name: saas_frontend
    ports:
      - "80:80" # El frontend estará disponible en http://localhost
    depends_on:
      - backend

volumes:
  pgdata: